CREATE TABLE RealEstateAgents (
    AgentID INT PRIMARY KEY IDENTITY,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    PhoneNumber NVARCHAR(20),
    Office NVARCHAR(100),
    CreatedAt DATETIME DEFAULT GETDATE()
);